-- require("core.plugin_config.neoscroll")
require("core.plugin_config.neovide")
require("core.plugin_config.neoscroll")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.tabby")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.lsp-color")
